return {
  'nvim-treesitter/nvim-treesitter',
  branch = 'master',
  lazy = false,
  build = ':TSUpdate',
  opts = {
    ensure_installed = {
      'bash',
      'c',
      'c_sharp',
      'comment',
      'commonlisp',
      'cpp',
      'css',
      'csv',
      'diff',
      'dockerfile',
      'gitignore',
      'go',
      'gomod',
      'gosum',
      'gowork',
      'html',
      'hyprlang',
      'java',
      'javadoc',
      'javascript',
      'json',
      'lua',
      'luadoc',
      'markdown',
      'markdown_inline',
      'prolog',
      'python',
      'sql',
      'toml',
      'vim',
      'xml',
    },
    highlight = { enable = true },
    indent = { enable = false },
  },
  config = function(_, opts)
    vim.filetype.add({
      pattern = { ['.*/hypr/.*%.conf'] = 'hyprlang' },
    })
    require('nvim-treesitter.configs').setup(opts)
  end,
}
